packages:
  - "."
allowBuilds:
  better-sqlite3: true
  "@clerk/shared": true
  "@parcel/watcher": true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
